# Generated by Django 2.2.11 on 2020-03-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200322_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='image',
            field=models.ImageField(blank=True, upload_to='webapp/images'),
        ),
    ]
