# Generated by Django 2.2.11 on 2020-03-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_categories_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='cost',
            field=models.DecimalField(decimal_places=3, default=10, max_digits=10),
        ),
        migrations.AddField(
            model_name='items',
            name='features',
            field=models.TextField(default='higly recomended'),
        ),
    ]
