# Generated by Django 2.2.11 on 2020-03-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20200322_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='categories',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='items',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='items',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
